apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    type: frontend
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: frontend
        name: ngnix-ppod
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend
